In [8]:
import numpy as np
import time

In [9]:
#Sudoku puzzle
sudoku = np.array([[0,0,0,8,0,0,6,9,4],
                 [0,0,0,0,0,0,0,7,0],
                 [0,6,0,2,1,0,0,0,0],
                 [0,0,8,0,0,0,9,0,7],
                 [0,2,0,0,6,0,0,5,0],
                 [1,0,9,0,0,0,3,0,0],
                 [0,0,0,0,2,7,0,3,0],
                 [0,7,0,0,0,0,0,0,0],
                 [2,9,5,0,0,8,0,0,0]])

In [10]:
#Function that takes in a sudoku puzzle and prints out the solved result
def solve_sudoku(sudoku):
    for row in range(9):
        for col in range(9):
            if sudoku[row][col] == 0:
                for num in range(1,10):
                    if can_place_number(row,col,num):
                        sudoku[row][col] = num
                        solve_sudoku(sudoku)
                        sudoku[row][col] = 0
                return
    print(sudoku)

In [11]:
#Function that checks out whether a given number can be placed at the included row and column of the sudoku puzzle. 
def can_place_number(row,col,num):
    
    #check if number "n" is in the adjacent row and column
    if num in sudoku[row,:]:
        return False
    elif num in sudoku[:,col]:
        return False
    
    #Checks if number "n" is in its respective 3x3 square
    row = (row//3)*3
    col = (col//3)*3
    if num in sudoku[row:row+3,
                   col:col+3]:
        return False
    
    return True #return true if we can put number n in that x,y coordinate

In [12]:
#Check time to see how fast the solver solved it
start_t = time.time()
solve_sudoku(sudoku) #<========= Sodoku Solver
stop_t = time.time()

[[5 1 2 8 7 3 6 9 4]
 [8 3 4 6 5 9 2 7 1]
 [9 6 7 2 1 4 5 8 3]
 [6 5 8 3 4 2 9 1 7]
 [7 2 3 9 6 1 4 5 8]
 [1 4 9 7 8 5 3 6 2]
 [4 8 6 5 2 7 1 3 9]
 [3 7 1 4 9 6 8 2 5]
 [2 9 5 1 3 8 7 4 6]]


In [13]:
print((stop_t - start_t)*1000)

781.7096710205078


In [14]:
##Code written with <3 by /u/literallyonfire